version: '3'
services:
  realtime:
    restart: always
    build:
      args:
        - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      context: .
      dockerfile: ./Dockerfile.local
    depends_on:
      - redis-server
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - PORT=3002
      - REDIS_URL=redis://:password@redis-server:6379
    env_file:
      - .env
    expose:
      - 3002
    ports:
      - 3002:3002
    volumes:
      - /app/node_modules
      - .:/app
  redis-server:
    image: redis
    command: redis-server --appendonly yes
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - ./redis-volume:/data
