name: test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build --build-arg DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} -t clockmarket/realtime:latest .
      - name: Run Unit Tests
        run: docker run clockmarket/realtime:latest yarn test
        env:
          CI: true
