name: test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build --build-arg DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: npm test
        env:
          CI: true
